[tool.poetry]
name = "libtimed"
version = "0.1.0"
description = "Library to intreact with timed webapp."
authors = [
  "Arthur Deierlein <arthur.deierlein@adfinis.com>",
  "Gian Klug <gian.klug@adfinis.com>",
]
readme = "README.md"
packages = [{ include = "libtimed", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.3.2"
isort = "^5.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
